/****************************************************************************
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
****************************************************************************/

/* file generated by 'font2openvg' tool by Mazatech S.r.l. - http://www.mazatech.com */

#ifndef VERA_FONT_H
#define VERA_FONT_H

#include "font_common.h"

#ifdef __cplusplus
extern "C" {
#endif

// the vera font structure
extern Font vera_font;

// initialize vera font
VGErrorCode veraFontInit(void);

// destroy vera font
void veraFontDestroy(void);

#ifdef __cplusplus
}
#endif

#endif /* VERA_FONT_H */
